### ISSUE TITLE
Bug creating migration folder in docker image

### ISSUE THREAD

**Issue by erikbra** [grate-devs/grate#89]
There seems to be a bug, when creating the migrations folder in the container. I get the following:

```
Unhandled exception: System.IO.IOException: The file '/app/grate' already exists.
   at System.IO.FileSystem.CreateDirectory(String )
   at System.IO.Directory.CreateDirectory(String )
   at grate.Migration.GrateMigrator.CreateChangeDropFolder(String folder)
   at grate.Migration.GrateMigrator.Migrate()
   at grate.Commands.MigrateCommand.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   (...)
```

Repro: 

* Copy your database scripts to the `./my_scripts` folder.
* Create an environment variable, CONNECTIONSTRING, on the host,with your connection string.
* Create a simple Dockerfile like this:

```Dockerfile
FROM erikbra/grate:latest
COPY ./my_scripts ./db
ENTRYPOINT ./grate -f=db --connectionstring "$CONNECTIONSTRING"
```

* build and run it like this:

```bash
 docker build -t my-db-image .
 docker run --rm -e CONNECTIONSTRING my-db-image
```

Observe the error.

**Comment by erikbra** [comment]
Pseudo, schmeudo... it's working ;)
